name: 'Build MPAS'
description: 'Build MPAS-Atmosphere with specified compiler configuration'

inputs:
  compiler:
    description: 'Compiler family (gcc, nvhpc, oneapi, etc.)'
    required: true
  use-pio:
    description: 'Use PIO library (true/false)'
    required: false
    default: 'false'
  openacc:
    description: 'Enable OpenACC (true/false)'
    required: false
    default: 'false'
  build-timeout:
    description: 'Build timeout in minutes'
    required: false
    default: '20'

outputs:
  executable:
    description: 'Path to built executable'
    value: ${{ steps.build.outputs.executable }}

runs:
  using: 'composite'
  steps:
    - name: Interrogate Runtime Environment
      shell: bash
      run: |
        if [ -f .github/workflows/interrogate_env.sh ]; then
          chmod +x .github/workflows/interrogate_env.sh
          .github/workflows/interrogate_env.sh
        else
          echo "=== Environment ==="
          echo "CC=${CC:-not set}"
          echo "FC=${FC:-not set}"
          which mpicc 2>/dev/null || echo "mpicc not found"
          which mpifort 2>/dev/null || echo "mpifort not found"
        fi

    - name: Build MPAS-A
      id: build
      shell: bash
      run: |
        # Source container environment if available
        # This sets NETCDF, PNETCDF, PIO, and other library paths
        if [ -f /container/config_env.sh ]; then
          echo "Sourcing container environment from /container/config_env.sh"
          source /container/config_env.sh
        fi
        
        # Map compiler input to COMPILER_FAMILY if not already set
        # The container should set this, but we provide a fallback
        if [ -z "${COMPILER_FAMILY}" ]; then
          case "${{ inputs.compiler }}" in
            gfortran|gnu)
              export COMPILER_FAMILY="gcc"
              ;;
            nvhpc|nvfortran)
              export COMPILER_FAMILY="nvhpc"
              ;;
            intel|ifx|ifort)
              export COMPILER_FAMILY="oneapi"
              ;;
            llvm|flang)
              export COMPILER_FAMILY="clang"
              ;;
            *)
              export COMPILER_FAMILY="${{ inputs.compiler }}"
              ;;
          esac
        fi
        
        # Set up I/O configuration
        if [ "${{ inputs.use-pio }}" = "true" ]; then
          export PIO_ROOT=${PIO_ROOT:-/container/pio}
          export USE_PIO2=true
        else
          unset PIO
          export USE_PIO2=false
        fi
        
        # Set up accelerator configuration
        if [ "${{ inputs.openacc }}" = "true" ]; then
          export OPENACC=true
        fi
        
        echo "Build configuration:"
        echo "  Compiler input: ${{ inputs.compiler }}"
        echo "  COMPILER_FAMILY: ${COMPILER_FAMILY}"
        echo "  NETCDF: ${NETCDF:-not set}"
        echo "  PNETCDF: ${PNETCDF:-not set}"
        echo "  USE_PIO2: ${USE_PIO2}"
        echo "  OPENACC: ${OPENACC:-false}"
        
        # Map COMPILER_FAMILY to make target
        case "${COMPILER_FAMILY}" in
          aocc|clang)  MAKE_TARGET="llvm" ;;
          gcc)         MAKE_TARGET="gfortran" ;;
          oneapi)      MAKE_TARGET="intel" ;;
          nvhpc)       MAKE_TARGET="nvhpc" ;;
          *)
            echo "::error::Unrecognized COMPILER_FAMILY=${COMPILER_FAMILY}"
            exit 1
            ;;
        esac

        echo "  Make target: ${MAKE_TARGET}"
        echo "  Parallel jobs: ${MAKE_J_PROCS:-$(nproc)}"

        timeout ${{ inputs.build-timeout }}m \
          make ${MAKE_TARGET} CORE=atmosphere --jobs ${MAKE_J_PROCS:-$(nproc)}
        
        # Set output
        echo "executable=$(pwd)/atmosphere_model" >> $GITHUB_OUTPUT

    - name: Verify executable
      shell: bash
      run: |
        if [ ! -f atmosphere_model ]; then
          echo "ERROR: atmosphere_model not found!"
          exit 1
        fi
        ls -la atmosphere_model
        file atmosphere_model
