name: 'Validate MPAS Logs'
description: 'Validate MPAS-Atmosphere output logs against reference'

inputs:
  logs-path:
    description: 'Path to directory containing log artifacts'
    required: true
  reference-log:
    description: 'Path to reference log file'
    required: false
    default: '.github/test-cases/240km/reference_log.atmosphere.0000.out'
  log-filter:
    description: 'Only validate log directories whose name contains this string'
    required: false
    default: ''
  expected-configs:
    description: 'Comma-separated list of expected config names; missing ones shown as NO_LOG'
    required: false
    default: ''

outputs:
  status:
    description: 'Validation status (pass/fail)'
    value: ${{ steps.validate.outputs.status }}
  summary:
    description: 'Validation summary line'
    value: ${{ steps.validate.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: List log artifacts
      shell: bash
      run: |
        echo "=== Log artifacts ==="
        if [ -d "${{ inputs.logs-path }}" ]; then
          ls -la "${{ inputs.logs-path }}/"
          find "${{ inputs.logs-path }}" -name "*.out" | sort | head -30
        else
          echo "WARNING: Logs directory not found: ${{ inputs.logs-path }}"
        fi

    - name: Validate logs against reference
      id: validate
      shell: bash
      run: |
        SCRIPT_DIR="${GITHUB_ACTION_PATH:-$(dirname "$0")}"
        SCRIPT="${SCRIPT_DIR}/compare_logs.py"
        if [ ! -f "${SCRIPT}" ]; then
          SCRIPT=".github/actions/validate-logs/compare_logs.py"
        fi

        FILTER_ARGS=""
        if [ -n "${{ inputs.log-filter }}" ]; then
          FILTER_ARGS="--filter ${{ inputs.log-filter }}"
        fi

        EXPECTED_ARGS=""
        if [ -n "${{ inputs.expected-configs }}" ]; then
          EXPECTED_ARGS="--expected ${{ inputs.expected-configs }}"
        fi

        set +e
        python "${SCRIPT}" \
          "${{ inputs.logs-path }}" \
          "${{ inputs.reference-log }}" \
          --allow-missing \
          --summary-file "$GITHUB_STEP_SUMMARY" \
          ${FILTER_ARGS} \
          ${EXPECTED_ARGS}
        VALIDATE_STATUS=$?
        set -e

        if [ $VALIDATE_STATUS -eq 0 ]; then
          echo "status=pass" >> $GITHUB_OUTPUT
          echo "summary=All validations passed" >> $GITHUB_OUTPUT
        else
          echo "status=fail" >> $GITHUB_OUTPUT
          echo "summary=Some validations failed" >> $GITHUB_OUTPUT
          exit 1
        fi
