name: 'Perturb Initial Conditions'
description: >
  Apply O(10^-14) perturbation to the theta field in an MPAS initial conditions
  file. Used to generate ensemble diversity for the Ensemble Consistency Test.
  This is a placeholder until native perturbation support is added to MPAS-A.

inputs:
  ic-file:
    description: 'Path to MPAS initial conditions NetCDF file (modified in place)'
    required: true
  seed:
    description: 'Integer seed for reproducible perturbation (unique per ensemble member)'
    required: true
  magnitude:
    description: 'Perturbation magnitude (default: 1e-14)'
    required: false
    default: '1e-14'

runs:
  using: 'composite'
  steps:
    - name: Install netCDF4
      shell: bash
      run: |
        python3 -m ensurepip --upgrade 2>/dev/null || true
        python3 -m pip install netCDF4 numpy

    - name: Perturb theta field
      shell: bash
      run: |
        python3 ${{ github.action_path }}/perturb_theta.py \
          "${{ inputs.ic-file }}" \
          --seed ${{ inputs.seed }} \
          --magnitude ${{ inputs.magnitude }}
