name: 'Run MPAS'
description: 'Run MPAS-Atmosphere test case'

inputs:
  executable:
    description: 'Path to atmosphere_model executable'
    required: false
    default: './atmosphere_model'
  num-procs:
    description: 'Number of MPI processes'
    required: false
    default: '1'
  run-duration:
    description: 'Run duration (format: D_HH:MM:SS). Overrides config.env default.'
    required: false
    default: ''
  restart-interval:
    description: 'Restart output interval (format: D_HH:MM:SS). Overrides config.env default.'
    required: false
    default: ''
  resolution:
    description: 'Test case resolution name (e.g., 240km). Used to find archive and config under .github/test-cases/<resolution>/'
    required: false
    default: '240km'
  data-repo:
    description: 'GitHub repo hosting test case archives (org/repo format)'
    required: false
    default: 'NCAR/mpas-ci-data'
  mpi-impl:
    description: 'MPI implementation (openmpi, mpich)'
    required: false
    default: ''
  run-timeout:
    description: 'Run timeout in minutes. Overrides config.env default.'
    required: false
    default: ''
  working-dir:
    description: 'Working directory name for the run'
    required: false
    default: ''

outputs:
  log-dir:
    description: 'Directory containing log files'
    value: ${{ steps.run.outputs.log-dir }}
  status:
    description: 'Run status (success/failed)'
    value: ${{ steps.run.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Load test case configuration
      id: config
      shell: bash
      run: |
        RESOLUTION="${{ inputs.resolution }}"
        CONFIG_FILE=".github/test-cases/${RESOLUTION}/config.env"
        
        # Defaults
        DURATION="0_06:00:00"
        RESTART="0_06:00:00"
        TIMEOUT="20"
        
        # Load from config.env if it exists
        if [ -f "${CONFIG_FILE}" ]; then
          echo "Loading config from ${CONFIG_FILE}"
          source "${CONFIG_FILE}"
          DURATION="${RUN_DURATION:-${DURATION}}"
          RESTART="${RESTART_INTERVAL:-${RESTART}}"
          TIMEOUT="${RUN_TIMEOUT:-${TIMEOUT}}"
        fi
        
        # Apply explicit overrides from action inputs
        if [ -n "${{ inputs.run-duration }}" ]; then
          DURATION="${{ inputs.run-duration }}"
        fi
        if [ -n "${{ inputs.restart-interval }}" ]; then
          RESTART="${{ inputs.restart-interval }}"
        fi
        if [ -n "${{ inputs.run-timeout }}" ]; then
          TIMEOUT="${{ inputs.run-timeout }}"
        fi
        
        # Determine working directory
        WORKDIR="${{ inputs.working-dir }}"
        if [ -z "${WORKDIR}" ]; then
          WORKDIR="run-${RESOLUTION}"
        fi
        
        echo "duration=${DURATION}" >> $GITHUB_OUTPUT
        echo "restart=${RESTART}" >> $GITHUB_OUTPUT
        echo "timeout=${TIMEOUT}" >> $GITHUB_OUTPUT
        echo "workdir=${WORKDIR}" >> $GITHUB_OUTPUT
        echo "resolution=${RESOLUTION}" >> $GITHUB_OUTPUT
        
        echo "=== Resolved test case configuration ==="
        echo "  Resolution: ${RESOLUTION}"
        echo "  Duration:   ${DURATION}"
        echo "  Restart:    ${RESTART}"
        echo "  Timeout:    ${TIMEOUT}m"
        echo "  Work dir:   ${WORKDIR}"

    - name: Download test case
      uses: ./.github/actions/download-testdata
      id: download
      with:
        test-case: ${{ inputs.resolution }}
        dest-dir: ${{ steps.config.outputs.workdir }}
        data-repo: ${{ inputs.data-repo }}

    - name: Link executable
      shell: bash
      run: |
        WORKDIR="${{ steps.config.outputs.workdir }}"
        chmod +x ${{ inputs.executable }}
        ln -sf $(realpath ${{ inputs.executable }}) "${WORKDIR}/atmosphere_model"

    - name: Configure namelist
      shell: bash
      working-directory: ${{ steps.config.outputs.workdir }}
      run: |
        DURATION="${{ steps.config.outputs.duration }}"
        RESTART="${{ steps.config.outputs.restart }}"
        
        # Modify run duration
        sed -i "s/config_run_duration = '[^']*'/config_run_duration = '${DURATION}'/" namelist.atmosphere
        
        # Modify restart interval
        sed -i '/<immutable_stream name="restart"/,/\/>/ s/output_interval="[^"]*"/output_interval="'"${RESTART}"'"/' streams.atmosphere
        
        echo "=== Namelist configuration ==="
        grep config_run_duration namelist.atmosphere

    - name: Run MPAS-A
      id: run
      shell: bash
      working-directory: ${{ steps.config.outputs.workdir }}
      run: |
        TIMEOUT="${{ steps.config.outputs.timeout }}"
        
        # Source container environment if available
        if [ -f /container/config_env.sh ]; then
          source /container/config_env.sh
        fi
        
        # Set MPI implementation
        if [ -n "${{ inputs.mpi-impl }}" ]; then
          export MPI_IMPL="${{ inputs.mpi-impl }}"
        fi
        
        # Set MPI flags
        MPI_FLAGS=""
        if [ "${MPI_IMPL}" = "openmpi" ]; then
          MPI_FLAGS="--allow-run-as-root --oversubscribe"
        fi
        
        # Set unlimited stack size
        ulimit -s unlimited 2>/dev/null || echo "Warning: Could not set unlimited stack size"
        
        echo "=== Run configuration ==="
        echo "  Resolution: ${{ steps.config.outputs.resolution }}"
        echo "  Processors: ${{ inputs.num-procs }}"
        echo "  Duration: ${{ steps.config.outputs.duration }}"
        echo "  MPI_IMPL: ${MPI_IMPL:-auto}"
        echo "  MPI_FLAGS: ${MPI_FLAGS}"
        echo "  Stack limit: $(ulimit -s)"
        echo "  Available CPUs: $(nproc 2>/dev/null || echo unknown)"
        echo "  Available RAM: $(free -m 2>/dev/null | awk '/^Mem:/{print $2 "MB"}' || echo unknown)"
        echo "  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:-not set}"
        
        # Run model
        set +e
        timeout ${TIMEOUT}m mpirun -n ${{ inputs.num-procs }} ${MPI_FLAGS} ./atmosphere_model
        RUN_STATUS=$?
        set -e
        
        # Set outputs
        echo "log-dir=$(pwd)" >> $GITHUB_OUTPUT
        echo "run-exit-code=${RUN_STATUS}" >> $GITHUB_OUTPUT
        if [ $RUN_STATUS -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "::warning::Model run exited with status $RUN_STATUS"
        fi

    - name: List output files
      shell: bash
      if: always()
      run: |
        WORKDIR="${{ steps.config.outputs.workdir }}"
        echo "=== Output files ==="
        if [ -d "${WORKDIR}" ]; then
          cd "${WORKDIR}"
          ls -la log.* 2>/dev/null || echo "No log files found"
          ls -la *.nc 2>/dev/null || echo "No NetCDF files found"
        else
          echo "Working directory ${WORKDIR} does not exist"
        fi

    - name: Check run status
      shell: bash
      if: always()
      run: |
        if [ "${{ steps.run.outputs.status }}" = "failed" ]; then
          echo "::error::MPAS model run failed with exit code ${{ steps.run.outputs.run-exit-code }}"
          exit 1
        fi
